spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME:javatechie}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      initialization-fail-timeout: -1
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update   # options: none, validate, update, create, create-drop
    show-sql: true       # logs SQL queries in console
    properties:
      hibernate:
        format_sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect